### ISSUE TITLE
GitHub project | 3 team members

### ISSUE THREAD

**Issue by DanteAlonsoHT** [DanteAlonsoHT/JavaScript-Capstone#22]
Link to go to Github Project: 👇 
https://github.com/users/DanteAlonsoHT/projects/1

**Note: We are 3 members.**

**Comment by henatan99** [comment]
Hi @DanteAlonsoHT , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [ ] The Kanban board is expected to have 20 tasks for 3 members; 5 group tasks, and 15 individual tasks assigned to the 3 members with 5 tasks each. I can only see you have just 3 group tasks on the Kanban board. Kindly complete assigning the tasks. 
- [ ] There should be a circle with the user's avatar on each card. Kindly see the example below and make changes accordingly. :pray: 

![image](https://user-images.githubusercontent.com/64894927/132263146-d38af8e0-ea80-455e-9192-e630e28f28dc.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vichuge** [comment]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
